apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.0
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx
            readOnly: true
          - name: html-config
            mountPath: /usr/share/nginx/html
            readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: html-config
          configMap:
            name: html-config
